//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.24 at 01:07:24 PM CET 
//


package generatedFromXSD;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generatedFromXSD package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generatedFromXSD
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XInvoice }
     * 
     */
    public XInvoice createXInvoice() {
        return new XInvoice();
    }

    /**
     * Create an instance of {@link GetCostRequest }
     * 
     */
    public GetCostRequest createGetCostRequest() {
        return new GetCostRequest();
    }

    /**
     * Create an instance of {@link GetInputVatRequest }
     * 
     */
    public GetInputVatRequest createGetInputVatRequest() {
        return new GetInputVatRequest();
    }

    /**
     * Create an instance of {@link GetInovicesRequest }
     * 
     */
    public GetInovicesRequest createGetInovicesRequest() {
        return new GetInovicesRequest();
    }

    /**
     * Create an instance of {@link GetCostResponse }
     * 
     */
    public GetCostResponse createGetCostResponse() {
        return new GetCostResponse();
    }

    /**
     * Create an instance of {@link GetOutputVatResponse }
     * 
     */
    public GetOutputVatResponse createGetOutputVatResponse() {
        return new GetOutputVatResponse();
    }

    /**
     * Create an instance of {@link AddInvoiceResponse }
     * 
     */
    public AddInvoiceResponse createAddInvoiceResponse() {
        return new AddInvoiceResponse();
    }

    /**
     * Create an instance of {@link GetAllInvoicesResponse }
     * 
     */
    public GetAllInvoicesResponse createGetAllInvoicesResponse() {
        return new GetAllInvoicesResponse();
    }

    /**
     * Create an instance of {@link GetInvoicesResponse }
     * 
     */
    public GetInvoicesResponse createGetInvoicesResponse() {
        return new GetInvoicesResponse();
    }

    /**
     * Create an instance of {@link GetIncomeRequest }
     * 
     */
    public GetIncomeRequest createGetIncomeRequest() {
        return new GetIncomeRequest();
    }

    /**
     * Create an instance of {@link GetInputVatResponse }
     * 
     */
    public GetInputVatResponse createGetInputVatResponse() {
        return new GetInputVatResponse();
    }

    /**
     * Create an instance of {@link GetIncomeResponse }
     * 
     */
    public GetIncomeResponse createGetIncomeResponse() {
        return new GetIncomeResponse();
    }

    /**
     * Create an instance of {@link GetOutputVatRequest }
     * 
     */
    public GetOutputVatRequest createGetOutputVatRequest() {
        return new GetOutputVatRequest();
    }

    /**
     * Create an instance of {@link DeleteInvoiceRequest }
     * 
     */
    public DeleteInvoiceRequest createDeleteInvoiceRequest() {
        return new DeleteInvoiceRequest();
    }

    /**
     * Create an instance of {@link UpdateInvoiceRequest }
     * 
     */
    public UpdateInvoiceRequest createUpdateInvoiceRequest() {
        return new UpdateInvoiceRequest();
    }

    /**
     * Create an instance of {@link UpdateInvoiceResponse }
     * 
     */
    public UpdateInvoiceResponse createUpdateInvoiceResponse() {
        return new UpdateInvoiceResponse();
    }

    /**
     * Create an instance of {@link AddInvoiceRequest }
     * 
     */
    public AddInvoiceRequest createAddInvoiceRequest() {
        return new AddInvoiceRequest();
    }

    /**
     * Create an instance of {@link GetAllInvoicesRequest }
     * 
     */
    public GetAllInvoicesRequest createGetAllInvoicesRequest() {
        return new GetAllInvoicesRequest();
    }

    /**
     * Create an instance of {@link DeleteInvoiceResponse }
     * 
     */
    public DeleteInvoiceResponse createDeleteInvoiceResponse() {
        return new DeleteInvoiceResponse();
    }

    /**
     * Create an instance of {@link XInvoice.XSeller }
     * 
     */
    public XInvoice.XSeller createXInvoiceXSeller() {
        return new XInvoice.XSeller();
    }

    /**
     * Create an instance of {@link XInvoice.XBuyer }
     * 
     */
    public XInvoice.XBuyer createXInvoiceXBuyer() {
        return new XInvoice.XBuyer();
    }

    /**
     * Create an instance of {@link XInvoice.XEntreis }
     * 
     */
    public XInvoice.XEntreis createXInvoiceXEntreis() {
        return new XInvoice.XEntreis();
    }

}
