//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.24 at 01:07:24 PM CET 
//


package generatedFromXSD;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for xInvoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xInvoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="xAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="xVatAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="xSeller">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="xId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="xName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="xTaxIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="xBuyer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="xId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="xName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="xTaxIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="xEntreis" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vatRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="vatAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xInvoice", propOrder = {
    "xId",
    "xAmount",
    "xVatAmount",
    "date",
    "xSeller",
    "xBuyer",
    "xEntreis"
})
public class XInvoice {

    protected int xId;
    @XmlElement(required = true)
    protected BigDecimal xAmount;
    @XmlElement(required = true)
    protected BigDecimal xVatAmount;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected XInvoice.XSeller xSeller;
    @XmlElement(required = true)
    protected XInvoice.XBuyer xBuyer;
    @XmlElement(required = true)
    protected List<XInvoice.XEntreis> xEntreis;

    /**
     * Gets the value of the xId property.
     * 
     */
    public int getXId() {
        return xId;
    }

    /**
     * Sets the value of the xId property.
     * 
     */
    public void setXId(int value) {
        this.xId = value;
    }

    /**
     * Gets the value of the xAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getXAmount() {
        return xAmount;
    }

    /**
     * Sets the value of the xAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setXAmount(BigDecimal value) {
        this.xAmount = value;
    }

    /**
     * Gets the value of the xVatAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getXVatAmount() {
        return xVatAmount;
    }

    /**
     * Sets the value of the xVatAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setXVatAmount(BigDecimal value) {
        this.xVatAmount = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the xSeller property.
     * 
     * @return
     *     possible object is
     *     {@link XInvoice.XSeller }
     *     
     */
    public XInvoice.XSeller getXSeller() {
        return xSeller;
    }

    /**
     * Sets the value of the xSeller property.
     * 
     * @param value
     *     allowed object is
     *     {@link XInvoice.XSeller }
     *     
     */
    public void setXSeller(XInvoice.XSeller value) {
        this.xSeller = value;
    }

    /**
     * Gets the value of the xBuyer property.
     * 
     * @return
     *     possible object is
     *     {@link XInvoice.XBuyer }
     *     
     */
    public XInvoice.XBuyer getXBuyer() {
        return xBuyer;
    }

    /**
     * Sets the value of the xBuyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XInvoice.XBuyer }
     *     
     */
    public void setXBuyer(XInvoice.XBuyer value) {
        this.xBuyer = value;
    }

    /**
     * Gets the value of the xEntreis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xEntreis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXEntreis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XInvoice.XEntreis }
     * 
     * 
     */
    public List<XInvoice.XEntreis> getXEntreis() {
        if (xEntreis == null) {
            xEntreis = new ArrayList<XInvoice.XEntreis>();
        }
        return this.xEntreis;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="xId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="xName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="xTaxIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xId",
        "xName",
        "xTaxIdentificationNumber"
    })
    public static class XBuyer {

        protected int xId;
        @XmlElement(required = true)
        protected String xName;
        @XmlElement(required = true)
        protected String xTaxIdentificationNumber;

        /**
         * Gets the value of the xId property.
         * 
         */
        public int getXId() {
            return xId;
        }

        /**
         * Sets the value of the xId property.
         * 
         */
        public void setXId(int value) {
            this.xId = value;
        }

        /**
         * Gets the value of the xName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXName() {
            return xName;
        }

        /**
         * Sets the value of the xName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXName(String value) {
            this.xName = value;
        }

        /**
         * Gets the value of the xTaxIdentificationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXTaxIdentificationNumber() {
            return xTaxIdentificationNumber;
        }

        /**
         * Sets the value of the xTaxIdentificationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXTaxIdentificationNumber(String value) {
            this.xTaxIdentificationNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vatRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="vatAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "desc",
        "vatRate",
        "amount",
        "vatAmount"
    })
    public static class XEntreis {

        protected int id;
        @XmlElement(required = true)
        protected String desc;
        protected int vatRate;
        @XmlElement(required = true)
        protected BigDecimal amount;
        @XmlElement(required = true)
        protected BigDecimal vatAmount;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

        /**
         * Gets the value of the vatRate property.
         * 
         */
        public int getVatRate() {
            return vatRate;
        }

        /**
         * Sets the value of the vatRate property.
         * 
         */
        public void setVatRate(int value) {
            this.vatRate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAmount(BigDecimal value) {
            this.amount = value;
        }

        /**
         * Gets the value of the vatAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getVatAmount() {
            return vatAmount;
        }

        /**
         * Sets the value of the vatAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setVatAmount(BigDecimal value) {
            this.vatAmount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="xId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="xName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="xTaxIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xId",
        "xName",
        "xTaxIdentificationNumber"
    })
    public static class XSeller {

        protected int xId;
        @XmlElement(required = true)
        protected String xName;
        @XmlElement(required = true)
        protected String xTaxIdentificationNumber;

        /**
         * Gets the value of the xId property.
         * 
         */
        public int getXId() {
            return xId;
        }

        /**
         * Sets the value of the xId property.
         * 
         */
        public void setXId(int value) {
            this.xId = value;
        }

        /**
         * Gets the value of the xName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXName() {
            return xName;
        }

        /**
         * Sets the value of the xName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXName(String value) {
            this.xName = value;
        }

        /**
         * Gets the value of the xTaxIdentificationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXTaxIdentificationNumber() {
            return xTaxIdentificationNumber;
        }

        /**
         * Sets the value of the xTaxIdentificationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXTaxIdentificationNumber(String value) {
            this.xTaxIdentificationNumber = value;
        }

    }

}
