//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.19 at 04:27:32 PM CET 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XInvoice }
     * 
     */
    public XInvoice createXInvoice() {
        return new XInvoice();
    }

    /**
     * Create an instance of {@link GetInovicesRequest }
     * 
     */
    public GetInovicesRequest createGetInovicesRequest() {
        return new GetInovicesRequest();
    }

    /**
     * Create an instance of {@link GetInvoicesResponse }
     * 
     */
    public GetInvoicesResponse createGetInvoicesResponse() {
        return new GetInvoicesResponse();
    }

    /**
     * Create an instance of {@link XInvoice.XSeller }
     * 
     */
    public XInvoice.XSeller createXInvoiceXSeller() {
        return new XInvoice.XSeller();
    }

    /**
     * Create an instance of {@link XInvoice.XBuyer }
     * 
     */
    public XInvoice.XBuyer createXInvoiceXBuyer() {
        return new XInvoice.XBuyer();
    }

    /**
     * Create an instance of {@link XInvoice.XEntreis }
     * 
     */
    public XInvoice.XEntreis createXInvoiceXEntreis() {
        return new XInvoice.XEntreis();
    }

}
